spring.application.name=SIGAC

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

server.port=8080
server.servlet.context-path=/

jwt.secret=sigacSystemJwtSecretKeyForAuthenticationAndAuthorizationPurposesOnly12345
jwt.expiration=86400000

logging.level.root=INFO
logging.level.com.example.sigac=DEBUG
logging.level.org.springframework.security=DEBUG
